formatter: "markdown"

version: "~> 0.20.0"


sections:
  show:
    - inputs
    - outputs
    - providers
    - requirements
    - resources

content: |-
  {{ include "docs/intro.md" }}

  ## Contents
  * [Requirements](#requirements)
  * [Providers](#providers)
  * [Resources](#resources)
  * [Inputs](#inputs)
  * [Outputs](#outputs)
  * [Examples](#examples)

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ include "docs/examples.md" }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

# output-values:
#   enabled: false
#   from: ""

# sort:
#   enabled: true
#   by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
