formatter: "markdown"

version: "~> 0.20.0"


sections:
  show:
    - inputs
    - outputs
    - providers
    - requirements
    - resources

content: |-
  {{ include "docs/intro.md" }}

  ## Contents
  * [Requirements](#requirements)
  * [Providers](#providers)
  * [Resources](#resources)
  * [Inputs](#inputs)
  * [Outputs](#outputs)
  * [Examples](#examples)

  {{ .Requirements }}

  {{ .Providers }}

  ## Resources
  | Name | Type |
  |------|------|
  {{- range .Module.Resources }}
  {{- $isResource := and $.Config.Sections.Resources (eq "resource" (printf "%s" .GetMode)) }}
  {{- $isDataResource := and $.Config.Sections.DataSources (eq "data source" (printf "%s" .GetMode)) }}
  {{- if or $isResource $isDataResource }}
  {{- $fullspec := ternary .URL (printf "[%s](%s)" .Spec .URL) .Spec }}
  | {{ $fullspec }} | {{ .GetMode }} |
  {{- if .Description }}
  |**Description:** {{  tostring .Description | sanitizeMarkdownTbl   }} ||
  {{- end }}
  {{- end }}
  {{- end }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ include "docs/examples.md" }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

# output-values:
#   enabled: false
#   from: ""

# sort:
#   enabled: true
#   by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
